# Generated by Django 5.2.3 on 2025-06-22 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_sharing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='md5_hash',
            field=models.CharField(blank=True, help_text='MD5 hash for file integrity', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='fileupload',
            name='sha256_hash',
            field=models.CharField(blank=True, help_text='SHA256 hash for file integrity', max_length=64, null=True),
        ),
    ]
