# Generated by Django 5.2.3 on 2025-06-27 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_sharing', '0004_shortlink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileupload',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='shortlink',
            name='created_by',
        ),
    ]
